version: "3"
services:
  app:
    build: .
    #image: flask_mongo:v0.0.1
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    environment:
       MONGODB_HOST: mongodb_container
       MONGODB_DATABASE: gitbase
    ports:
      - "5000:5000"

  mongodb_container:
    image: mongo:latest
    ports:
      - 27017:27017

networks:
   default:
     driver: bridge
